### ISSUE TITLE
User themes

### ISSUE THREAD

**Issue by icidasset** [fission-suite/drive#3]
Users would like to customize the look of their drive app.

## Current Solution

Currently we have a light and dark theme that changes based on the user's system preferences.

## Preferred Solution

Not sure how to approach this. Where do we draw the line?
If they define a theme, is it a fixed light or dark theme?
Does a theme have to define both?

Maybe something like this ...?

```yaml
accent: ...
accent_background: ...
body_background: ...
body_text: ...
subtle_text: ...
```

And finally, how would these themes be applied?
